name: cache_poc

on:
  workflow_dispatch:

jobs:
  first:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Create file
        run: echo "@@@" > ~/x.txt

      - name: Cache file
        uses: actions/cache/save@v3
        id: save-file
        with:
          path: |
            ~/x.txt
          key: CACHED_FILE

  second:
    needs: first
    name: test
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Restore cached file
        id: restore-file
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/x.txt
          key: CACHED_FILE
      - run: cat ~/x.txt
