name: cache_poc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install project
        run: npm install cpx

      - name: Cache mode_modules
        uses: actions/cache/save@v3
        id: save-file
        with:
          path: |
            ./node_modules
          key: npm-cache-${{ hashfiles('package-lock.json') }}

  test:
    needs: build
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Restore cached
        id: restore-file
        uses: actions/cache/restore@v3
        with:
          path: |
            ./node_modules
          key: npm-cache-${{ hashfiles('package-lock.json') }}
      - run: npx cpx -h
