name: cache_poc

on:
  workflow_dispatch:

jobs:
  first:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create file
        run: npm install cpx

      - name: Cache file
        uses: actions/cache/save@v3
        id: save-file
        with:
          path: |
            ./node_modules
          key: npm-cache-${{ hashfiles('package-lock.json') }}
          restore-key: npm-cache-${{ hashfiles('package-lock.json') }}

  second:
    needs: first
    name: test
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Restore cached file
        id: restore-file
        uses: actions/cache/restore@v3
        with:
          path: |
            ./node_modules
          key: npm-cache-${{ hashfiles('package-lock.json') }}
      - run: npx cpx
