name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: npm install

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: npm-cache-${{ hashfiles('package-lock.json') }}

      # - name: Build docker image
      #   run: docker build -t js-utils .

      # - name: Run tests
      #   run: docker run --rm js-utils
  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: npm-cache-${{ hashfiles('package-lock.json') }}

      - name: Tests
        run: npm test
